version: '3.8'

services:
  frontend:
    container_name: encontreja-frontend
    image: "encontreja-frontend"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    command: ["yarn", "dev"]